trigger:
  - main
  
  jobs:
  - job: Build_and_Deploy_Frontend
    displayName: 'Build and Deploy Frontend'
    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
  
    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Frontend'
  
    - task: AzureStaticWebApp@0
      inputs:
        app_location: 'frontend'
        output_location: 'frontend/dist'
        azure_static_web_apps_api_token: $(deployment_token)
      displayName: 'Deploy Frontend to Azure Static Web Apps'
  
  - job: Deploy_Backend
    displayName: 'Deploy Backend'
    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
      displayName: 'Use Python 3.x'
  
    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r SalasComputadoras/requirements.txt
      displayName: 'Install Python Dependencies'
  
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/SalasComputadoras'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true
  
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'your-azure-subscription'
        appName: 'your-backend-app-service-name'
        package: '$(Build.ArtifactStagingDirectory)/backend.zip'
      displayName: 'Deploy Backend to Azure App Service'
  